spring:
  data:
    cassandra:
      keyspace-name: main
      username: GmPrkHUqeZbJiuUupOpDfeuQ
      password: xzLv,QUfNTR1PkgRZGnlu8p,Z94xeM4.SDPSRYHcra.QUum-ZAGog-zp.g-eCzMeJE,rBxjYvPJdL.uX6tRZIc_yLJR2CsG.eaQb04g-U39inPgkAXY3jj+lfCqUlYe0
      schema-action: create-if-not-exists
      request:
        timeout: 59s
      connection:
        connect-timeout: 59s
        init-query-timeout: 59s
  main:
    allow-circular-references: true

datastax.astra:
    secure-connect-bundle: ./secure-connect.zip


astra.db:
    id: a8de01c7-3878-419c-b073-0f4eeb113d96-1
    region: europe-west1
    keyspace: main
    application.token: AstraCS:GmPrkHUqeZbJiuUupOpDfeuQ:8152c56d28825615859eb5e6b22f20b4a713b20059427236a22eb829b7851221


services:
  band-url: https://heroku-bands.herokuapp.com/bands/
  task-url: https://test-herokus1.herokuapp.com/tasks/
  user-url: https://mafias-user-service-app.herokuapp.com/api/users/
  weapon-url: https://weapon-service-v1.herokuapp.com/api/v1/weapons/


my:
  app:
    secret: AndrewReshetnyakAAAAAAAAAAAAAAAAaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
